### ISSUE TITLE
Feedback from Konrad2

### ISSUE THREAD

**Issue by cooljeanius** [cooljeanius/dawn_of_thunder#10]
See this post from @Konrad22 on the forums: 
https://forums.wesnoth.org/viewtopic.php?p=682649#p682649

**Comment by Konrad22** [comment]
https://github.com/cooljeanius/dawn_of_thunder/blob/673aed1eeb33f8e72d371f0ddb8b530e8eeb619c/scenarios/01_the_outpost.cfg#L70-L82

**Comment by cooljeanius** [comment]
hm, apparently the `{TURNS_RUN_OUT}` is missing in *all* the scenarios with turn limits, besides just the ones pointed out... I'll get to those later...

**Comment by cooljeanius** [comment]
linking to follow-up post with additional feedback for clarity: https://forums.wesnoth.org/viewtopic.php?p=682649#p682649

**Comment by cooljeanius** [comment]
> > S5
> > At the end of the scenario you get to keep the Elvish Hunters. Silam says that they won't cost upkeep, which is untrue. Only one of them is loyal. Perhaps an oversight?
> 
> > Hm, unsure what to do here since they all have the same number of traits currently... do I remove a trait from the 2 that currently don't have loyal to make room for it, or do I add an additional trait to the 1 that already has it, so that they each have 3 traits (4 on EASY)?
> 
> I'd suggest removing one of the traits.

Argh, I can't decide... what if I just did `upkeep=loyal` instead of using the trait?

**Comment by Konrad22** [comment]
> Argh, I can't decide... what if I just did `upkeep=loyal` instead of using the trait?
That would be the same as adding the trait on top, and you know it. xD
If you are willing to put in extra effort, you could delegate the decision to the player, make them pick the traits they want their elvish hunters to have. (From a list of the traits they have right now.)

**Comment by cooljeanius** [comment]
> > Argh, I can't decide... what if I just did `upkeep=loyal` instead of using the trait?
> 
> That would be the same as adding the trait on top, and you know it. xD If you are willing to put in extra effort, you could delegate the decision to the player, make them pick the traits they want their elvish hunters to have. (From a list of the traits they have right now.)

oh right I think I saw some other campaign that allowed players to do that... "A Group in a War" perhaps? Or "Trapped"?

**Comment by Konrad22** [comment]
> oh right I think I saw some other campaign that allowed players to do that... "A Group in a War" perhaps? Or "Trapped"?

A Group in War, the homebase scenario.

**Comment by cooljeanius** [comment]
> > oh right I think I saw some other campaign that allowed players to do that... "A Group in a War" perhaps? Or "Trapped"?
> 
> A Group in War, the homebase scenario.

OK, I copied over the relevant macros in 8a3a7ed, and started using them in a85a8c1,  so with that, I think I'm done with everything in this issue that I'm going to do...
