### ISSUE TITLE
fixme requests on dialogues

### ISSUE THREAD

**Issue by k-konami** [cooljeanius/dawn_of_thunder#11]
* redundant space character
====================================================================
1 scenarios/06_woodchoppers.cfg: 58 
2 scenarios/06_woodchoppers.cfg: 1495
3 units/faeries/fallenfaerie.cfg:41

* incorrect(or maybe) spelling , capitalization  & repetition of the same word
====================================================================
4 scenarios/08_grand_meeting.cfg:561  greenwood  --> Greenwood ?
5 units/faeries/fallenfaerie.cfg:41   fightm  -->  fight
6 units/humans-northguard/Northguard_Braveheart.cfg:19  lycantropy  -->  lycanthropy
7 units/humans-northguard/Northguard_Warrior.cfg:19  "to fight fight" -->  "to fight"
8 units/humans/GoldenMage.cfg:123  "Gold Magi Magi are"
9 utils/Special_notes.cfg:36  spell: tranform -> transform
10 units/humans/GreyMage.cfg:80 "timen" --> "time" ?  ,  "then their" --> "than their" ?
11 scenarios/11_dwarvish_gratitude.cfg:223   "ambushed by by trolls"

* need a period character
====================================================================
12 scenarios/08_grand_meeting.cfg:1657
13 units/elves/ElvishHalverdier.cfg:32

* has no period character.  Is it ok? (naration)
====================================================================
14 scenarios/09_underground.cfg:480
15 scenarios/09_underground.cfg:481

* Since this is an objective's line, period character is not usually used.
====================================================================
16 scenarios/10_subterranean_crossfire.cfg:703

*  1,2,3,4,5$  ->  1,2,3,4,5 Gold ?
====================================================================
17 utils/weapon_specials.cfg:91  text="<span color='#cccc33'>" + _ "1$" + "</span>"
18 utils/weapon_specials.cfg:111 text="<span color='#cccc33'>" + _ "2$" + "</span>"
19 utils/weapon_specials.cfg:131 text="<span color='#cccc33'>" + _ "3$" + "</span>"
20 utils/weapon_specials.cfg:151 text="<span color='#cccc33'>" + _ "4$" + "</span>"
21 utils/weapon_specials.cfg:171 text="<span color='#cccc33'>" + _ "5$" + "</span>"

* others 
====================================================================
22 scenarios/15_Wild_Steppe.cfg:321   name="Pelagius"  ( -->   name= _ "Pelagius" )
23 scenarios/18_Illuvèn.cfg:105  
   message= _ "God damn! Bah, who needs astral blades if you have maces..."
  ( "astral blade" is not used in this campaign  :) )  (def. in "ageless era" ?). 
24 units/naga/Naga_Hunter.cfg:29   "TODO" ? （unfinished description?）
25 utils/traits.cfg:28  description= _ "+5% defense and"
      "and" ... what?   ...  " MP +2" ?
 --
That is all.

**Comment by cooljeanius** [comment]
ok this ought to be fixed by [f74459b](https://github.com/cooljeanius/dawn_of_thunder/commit/f74459b789e2f93d8580de724d0ebfbb0e33a9c6)
