### ISSUE TITLE
S17  What happens with surrounding Mal Lirak and what happens without surrounding.

### ISSUE THREAD

**Issue by k-konami** [cooljeanius/dawn_of_thunder#12]
If Mal Lirak is surrounded from three sides, Mal Lirak escapes at that point and the scenario ends with a victory.
If Mal Lirak is defeated without being surrounded from less than three sides, Mal Lirak will die. (Likewise, the scenario ends in victory.)
 In either case, we cannot capture him. In other words, we can only let him escape or kill him.

( objective for win: Defeat all enemy leaders and Capture Mal Lirak )

**Comment by cooljeanius** [comment]
ok I think the wording ought to be improved now as of 43085bc, although I worry that it might be a bit too close to being a spoiler now...
