### ISSUE TITLE
theme files are obsolete

### ISSUE THREAD

**Issue by knyghtmare** [cooljeanius/dawn_of_thunder#5]
In 1.16 and above, both Cutscene and Cutscene-minimal themes are available in core.
These were from AtS but later mainlined so 1.10, 1.12, 1.14 add-ons should no longer have a need to keep duplicates.

**Comment by cooljeanius** [comment]
Oh I didn't even realize this add-on was shipping copies of those...

**Comment by knyghtmare** [comment]
> ...so just delete that whole directory, then?

yeah, not needed anymore

**Comment by cooljeanius** [comment]
ok so 01a9848 ought to have fixed this
