### ISSUE TITLE
Update maps to meet knyght's criteria for map quality

### ISSUE THREAD

**Issue by cooljeanius** [cooljeanius/dawn_of_thunder#8]
From wesnoth/wesnoth#7479, according to @knyghtmare, good maps should have:

1. More than 10 terrain types used. 
2. Map is actually visually appealing to look at, i.e., not too plain (this one is still kind of subjective IMO)
3. Map appearance uses the campaign's lore properly.
4. Uses embellishments.

**Comment by cooljeanius** [comment]
So yeah @knyghtmare I rechecked the first map and it turns out it does actually meet your criteria: it uses 14 types of base terrain (`Gs`, `Re`, `Gg`, `Hh`, `Rp`, `Cv`, `Kv`, `Ww`, `Wwf`, `Wwrg`, `Rd`, `Mm`, `Ce`, `Ke`), plenty of embellishments, and fits the campaign lore of being the southern edge of a forest

**Comment by knyghtmare** [comment]
> Map is actually visually appealing to look at, i.e., not too plain (this one is still kind of subjective IMO)

Still not impressed. Sorry

**Comment by cooljeanius** [comment]
> > Map is actually visually appealing to look at, i.e., not too plain (this one is still kind of subjective IMO)
> 
> Still not impressed. Sorry. Also, the Wesnoth Modders Guild have an impressive roster of map-makers: I mean you can ask for improvements there.

I think it's perfectly fine and you're just being too picky

**Comment by knyghtmare** [comment]
I mean whatever. it's your campaign. If you don't wanna update maps to higher quality, then don't

I am retiring soon anyways, so probably wont matter..

**Comment by cooljeanius** [comment]
hm, I wonder if there's actually a way to automate checking against these criteria? Opening each map in the editor and then counting the terrain types used by hand is going to be tedious...

**Comment by cooljeanius** [comment]
Discovered an error when trying to load the S03 map in the editor:
```
20230403 22:48:33 warning editor: format error in load map : Unknown tile in map: (Cv^Cvw) 'Cv^Cvw'
```
<img width="407" alt="Screen Shot 2023-04-03 at 22 48 44" src="https://user-images.githubusercontent.com/1388660/229674070-8cd108ff-3d71-457b-9598-cbe5054a34cb.png">
Any idea how to fix? The map loads successfully when playing normally in gameplay mode...

**Comment by cooljeanius** [comment]
ok I'll admit that the S07 map could use some work

**Comment by cooljeanius** [comment]
addition of the "help wanted" label is for the S07 map; it's a bit tricky there since adjusting the map will require adjusting the scenario code, too, since there is some terrain-dependent code in it

**Comment by cooljeanius** [comment]
Actually nvm; [c6f47b5](https://github.com/cooljeanius/dawn_of_thunder/commit/c6f47b57feb80eee2a238481ed4bd633be16dd6e) was probably enough.
